options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/grasacorporalapp/grasa-backend/api:latest',
        '-f',
        'Dockerfile.back',
        '.'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'grasa-backend',
        '--image',
        'europe-west1-docker.pkg.dev/grasacorporalapp/grasa-backend/api:latest',
        '--region',
        'europe-west1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'europe-west1-docker.pkg.dev/grasacorporalapp/grasa-backend/api:latest'

